### PR TITLE
Make behavior of unknown tags configurable

### LINKED ISSUE #33: Ignore unknown/wrong tags
Right now when the parser encounters some text in `[]` that is not a known tag, it gives an error. There should be at least an option to ignore those tags and either just leave them as is or remove them completely.

### PR DESCRIPTION
**Pull request by veger**
Unknown tags are treated as text, unless configuration is used to instead raise an exception.

Fixes #33

### CODE REVIEW

File: lib/ruby-bbcode.rb [hunk 1]
```diff
@@ -11,6 +12,22 @@
 module RubyBBCode
   include ::RubyBBCode::Tags
 
+  class << self
```
Comment (veger) [inline lib/ruby-bbcode.rb]: Tests are missing

**Comment by almaron** [comment]
A much neater solution. But I'd rather have an option to completely ignore those tags (i.e. not render anything) or treat them as text.

**Comment by almaron** [comment]
So maybe we can set the configuration to be slightly more flexible.
Like have `:exception`, `:text`, `:ignore` possibilities.

**Comment by veger** [comment]
you mean you want to hide the tags themselves and only show text in between?
Could be a neat option yes, let me see if we can change the code and grab this from existing `tag_info`
